FROM rabbitmq:3.12-management

# Instala herramientas necesarias
RUN apt-get update && apt-get install -y curl

# Descarga el archivo .ez directamente
RUN curl -L -o /plugins/rabbitmq_delayed_message_exchange.ez https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez

# Habilita el plugin
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

